/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zubair.alam' at '5/24/16 10:32 AM' with Gradle 2.9
 *
 * @author zubair.alam, @date 5/24/16 10:32 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
