/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zubair.alam' at '5/23/16 4:46 PM' with Gradle 2.9
 *
 * @author zubair.alam, @date 5/23/16 4:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
